apiVersion: apps/v1
kind: Deployment
metadata:
  name: hjgytd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hjgytd
  template:
    metadata:
      labels:
        app: hjgytd
    spec:
      containers:
      - image: okteto.dev/hjgytd:latest
        name: hjgytd
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "b19ba5e9-4e0f-4bf5-a78c-9df15b713d06"
        - name: Vless_Path
          value: "/vlfghr083"
        - name: Vmess_UUID
          value: "b19ba5e9-4e0f-4bf5-a78c-9df15b713d06"
        - name: Vmess_Path
          value: "/vmujnda564"
        - name: Share_Path
          value: "/v2link"
